### ISSUE TITLE
Add ReGenerator as git submodule

### ISSUE THREAD

**Issue by grzanka** [libamtrack/library#148]
Remove old R package generator, it can be retrieved from the history

**Comment by grzanka** [comment]
Remove also `scripts` subdirectory

**Comment by grzanka** [comment]
Remove also `R` `tests` directory

**Comment by Sharon131** [comment]
Added submodule, removed directories `distributions/R`, `scripts` and `test/R`. Is directory `test/C` is needed or can also be deleted?

**Comment by grzanka** [comment]
Where is the submodule added ? Is there any branch and PR for that ?

**Comment by Sharon131** [comment]
Changes were made on branch `r-wrapper-generator`. Pull request: #151
